### ISSUE TITLE
Form deserialization in other SKSE plugins

### ISSUE THREAD

**Issue by Verteiron** [SilverIce/JContainers#49]
Inside my own SKSE plugin, I am calling JContainers to deserialize form text in order to try and preserve compatibility with future versions should the string format change.

Right now though I'm doing it this way:
```cpp
if (JCAvailable()) {
		//Turn the string into a single-item JSON array, then get JContainers to retrieve the form.
		std::string formArrayString("[ \"" + formString + "\" ]");
		SInt32 tempJArray = JValue_objectFromPrototype(nullptr, formArrayString.c_str());
		result = JArray_getForm(nullptr, tempJArray, 0, nullptr);
		JValue_release(nullptr, tempJArray);

		return result;
	}
```

Obviously this is less than optimal (and seems to crash when called multiple times in a row), but there doesn't seem to be an exposed API for simply (de)serializing Forms and their strings. I have my own deserializer implemented but obviously if JContainers changes how forms are stored it will break. Is there a better way to do this or should I just assume that the string format won't change any time soon?

**Comment by SilverIce** [comment]
Unlikely this will ever change (due to bunch of JSON files in the outer world). I had an idea to implement something like `encodeForm`, `decodeForm` in JString before..

Do you use JC to pass the data? Wouldn't be simpler for you to fork JContainers and pick its lifetime and etc model and expose (via handles) your native objects into Skyrim?

That's strange, it shouldn't crash as there is no shared state between the calls. Which function causes this?

**Comment by Verteiron** [comment]
Well the interaction between my plugin code and JContainers is minimal, consisting mostly of passing some strings back and forth. My c++ knowledge is minimal and I'm trying not to duplicate functionality, just add some minimal stuff I need on the SKSE side where things are insanely fast compared to Papyrus. 

The crash actually happens within the "return result" statement, and only in the Release compilation, not while debugging (of course). It's mostly likely an issue on my end of things, as JC has always been rock solid for me. 

For now I'm just using my own code to get the form objects from the string; if the encoding is not likely to change I'll just stick to that.

Thanks!
